#!/usr/bin/env bash
# Installing nginx on our webserver

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
