#!/usr/bin/env bash
# redirecting a page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.github.com/besthor permanent; }' /etc/nginx/sites-enabled/default

service nginx restart
