#!/usr/bin/env bash
# redirecting a page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#sudo sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.github.com/besthor permanent; }' /etc/nginx/sites-enabled/default

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
