#!/usr/bin/env bash
# 404 configuration

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo sed -i 's|# server_name _;|server_name _;|' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me/ {\n\t\treturn 301 https://www.example.com/;\n\t}\n' /etc/nginx/sites-enabled/default
# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/error;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
