#!/usr/bin/env bash
# 404 configuration

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo sed -i 's|# server_name _;|server_name _;|' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me/ {\n\t\treturn 301 https://www.example.com/;\n\t}\n' /etc/nginx/sites-available/default
sudo mkdir -p /var/www/html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server {/a \
    error_page 404 /404.html;\
    location = /404.html {\
        internal;\
    }\
' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx reload
