#!/usr/bin/env bash
# check if less than 4 parameters are passed
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# assign parameters to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# transfer file using scp with strict host key checking disabled
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# check if the file transfer was successful
if [ $? -eq 0 ]
then
  echo "File transfer successful"
else
  echo "File transfer failed"
fi
